[project]
name = "pares-ordenados-geometria"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geomstats>=2.8.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.5",
]
